"""init

Revision ID: 75b364ae0ee4
Revises: 
Create Date: 2026-02-06 18:29:31.111283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b364ae0ee4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usr',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usr_email'), 'usr', ['email'], unique=True)
    op.create_table('booking',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('active', 'canceled', name='booking_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_start_time'), 'booking', ['start_time'], unique=False)
    op.create_index(op.f('ix_booking_table_id'), 'booking', ['table_id'], unique=False)
    op.create_index(op.f('ix_booking_user_id'), 'booking', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_user_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_table_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_start_time'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_usr_email'), table_name='usr')
    op.drop_table('usr')
    op.drop_table('table')
    # ### end Alembic commands ###
